### ISSUE TITLE
DeployerRepository created as in-memory

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-skipper#131]
`DeployerRepository` extends `DeployerRepositoryCustom` which is backed by `DeployerRepositoryImpl`. 
I'm amazed that `DeployerRepositoryImpl` doesn't blow up as essentially it autowires itself to its
```
@Autowired
public DeployerRepository deployerRepository;
```
And this instance of `DeployerRepository` is a proxy of `DeployerRepositoryImpl` and seeing from debugging it is backed by `MapKeyValueAdapter` which uses Map as store. This is slightly confusing and spring-data thinks that as well.

```
Spring Data JPA - Could not safely identify store assignment for repository candidate interface org.springframework.cloud.skipper.repository.DeployerRepository.
```

![skipper-jpa-tables-1](https://user-images.githubusercontent.com/50398/31171068-65aed3e4-a8f6-11e7-988d-dbb633cf5ed6.png)

**Comment by jvalkeal** [comment]
Classes in question are:
```
@RepositoryRestResource
public interface DeployerRepository extends PagingAndSortingRepository<Deployer, String>, DeployerRepositoryCustom {
}

public interface DeployerRepositoryCustom {

	Deployer findByNameRequired(String name);
}

public class DeployerRepositoryImpl implements DeployerRepositoryCustom {

	@Autowired
	private DeployerRepository deployerRepository;

	@Override
	public Deployer findByNameRequired(String name) {
		Deployer deployer = deployerRepository.findByName(name);
		if (deployer == null) {
			throw new SkipperException(String.format("Can not install, no deployer named '%s'", name));
		}
		return deployer;
	}
}
```

**Comment by olivergierke** [comment]
If you have multiple Spring Data stores on the classpath, the repositories bootstrap will switch to strict configuration mode, i.e. it will try to determine the backing datastore based on either a repository base interface (e.g. `JpaRepository`) or a store-specific annotation on the domain type managed (e.g. `@Entity` for JPA). It will not create a store repository instance if it cannot detect the store. So the log output you see is not some kind of confusion but the decision that `Deployer` is not a JPA entity (annotation missing?), so that Spring Data JPA will not back this repository.

**Comment by olivergierke** [comment]
Oh, no need to be amazed about the autowiring: the repository is backed by a factory bean that uses setter injection for the custom implementation part. Your custom repository is using field injection which is tied to the same injection phase as setter injection. I.e. there's no problem to create instances for both beans and wire them to each other.

**Comment by jvalkeal** [comment]
Yeah, I added some missing annotations and then things naturally blows up as `AppDeployer` in `Deployer` naturally cannot be serialised.
