### ISSUE TITLE
Create package delete command

### ISSUE THREAD

**Issue by AWeeks1** [spring-cloud/spring-cloud-skipper#331]
Currently, there is no way to delete or remove a package that has been uploaded. This can cause problems if you are only changing some metadata name + version (See https://github.com/spring-cloud/spring-cloud-skipper/issues/317) or if you want to make a small change to a package for testing (or if you upload a package by mistake) etc etc. 

This can be fixed with an opposite method to ` upload --path` which could be `remove package --package-name --package-version`, which would remove the package instantly and update the local db.

**Comment by markpollack** [comment]
Need to checkif there are any releases that reference this package, if so, it should not be deleted.

**Comment by markpollack** [comment]
2)  package delete service method
      check that it is a local type repo (DB backed)
      check that all releases for that package are in the state StatusCode.DELETED
              method PackageService.deleteAndCheckStatus()

**Comment by sabbyanandan** [comment]
Can we add the new command in 1.0.1, as an incremental release?

**Comment by markpollack** [comment]
Pretty bad experience not to be able to delete when in a dev cycle.

Looking into it, looks like this will trigger a renaming of the commands since ATM there is `delete` with no prefix that deletes a release so we would need to have `package delete`... which would be inconsistent with `list` that searches packages.  `we should have `package list` then.  Getting this naming right is important as you can't make such a breaking change later with commands.
