### ISSUE TITLE
Remove use of LRUCleaningResourceLoader

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-skipper#373]
Depending on the outcome of #337, add the ability to disable the `LRUCleaningResourceLoader`.

Local testing becomes frustrating on a disk space constrained machine 😬

**Comment by markpollack** [comment]
We are removing it completely, turns out to be harder to manage in terms of not deleting artifacts that are in the process of being deployed.  Has effectively been disabled since version 1.3.  On PCF where this issue first came up - we recommend using Boot disk space health indicator to restart the server if disk space gets low.  Will investigate use of Volume Service on PCF.  See #646
