### ISSUE TITLE
Review repository and Package Metadata mapping, introduce JPA managed relationship

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#383]
As a developer, I'd like to review 1-1 and 1-n relationship mappings. We would have to check the lifecycle of the CRUD methods.

Notes: 
1. repository is 1-n with pkg metadata
2. pkg-metadata is 1-1 with pkg-zip file

**Comment by markpollack** [comment]
After going through the implementation for this issue, imho, the current implementation where we manually mange the relationship between the repository and the metadata is better than a JPA managed alternative.  

The reason is that we are not directly supporting a "delete repository" feature that blindly would cascade the deletion of the packages.  One would need to check if any packages were currently released with a 'deployed' status.   Also, there is a fair amount of incidental complexity wrt to lazy initialization, Cascade Delete options, and circular references in jackson json der/seder as we are exposing the 'raw domain' objects over the wire. 

Also, removing a repository then implies the ability to add a repository at runtime, both of which impact the repository 'order' property. It is simpler and less complex,  for the admin of the skipper server to set the repositories to use at configuration time and set the order.  It doesn't seem like adding/removing repositories will be something done often.

We can introduce spring cloud config server support to change the overall configuration without a reboot.  Will create an issue to discuss.

Of note, we should add @RestResource(exported = false) to `RepositoryRepository` methods `save`, `delete` (and delete overloads) and `deleteAll`.  A new issue will be created.

We are paying a price managing the zip file as a byte[] field and not a class such as `PackageFile` in that may load extra bytes form the database which should instead be handled lazily.  Will create an issue to discuss that.
