### ISSUE TITLE
Spinnaker vs Skipper

### ISSUE THREAD

**Issue by thekalinga** [spring-cloud/spring-cloud-skipper#394]
Other than using Skipper with `Spring cloud data flow` & `Spring task launcher`, is there any compelling reason to use Skipper over Spinnaker?

Spinnaker is a production grade deployment tool & has large community support.

**Comment by markpollack** [comment]
Yes, several.  Skipper provides a declarative templating mechanism to describe the collection of Spring Boot apps to deploy and also a mechanism to discover/search for existing Spring Boot apps.  https://blog.switchbit.io/spring-cloud-skipper-as-a-service-broker/ is an interesting extension on top of what Skipper provides in this regard.   Skipper is more lightweight, one server and a relational database are the requirements.  Coming from the use case of supporting the evolution of Spring Cloud Stream applications deployed via Data Flow, a user in Cloud Foundry would not want to install and pay for the 8 or so applications that Spinnaker requires in order to provide upgrade capability to perhaps the same number of stream applications.

**Comment by thekalinga** [comment]
Thanks for your response

a. My assumption is that most organisations would want to use `Spinnaker` for the following reasons

1. Streamlined integration with multiple platforms (CF, AWS, GCP, K8S & others)
2. Workflow management (pipelines) starting from triggering build, automated tests, manual review, .., R/B deployment, Canary deployment, & more
3. Integration with Mail, Chat bots, SMS notifications, and many more

b. Plus, Most of the organisations would use `Consul`/`Eureka`/`ZK`/`EtcD`/`SkyDns`(Comes with `k8s`) for service registry which are battle tested.

Assuming that above justifications are reasonable enough to be used in any organisation, any  advantages of using `Skipper` looks superficial to me.

I just skimmed over the article. Could not find a convincing argument to develop a new library altogether when there are already a large number of tools that are solving similar problem.

Again, I'll read the article in detail & post any new my observations if I find any.

Do let me know if you have some solid reasoning.

**Comment by thekalinga** [comment]
As of now this library reminds me of `Spring XD` which tried to reinvent the wheel & came back to a much simpler model with `Spring Cloud Data Flow`

**Comment by sabbyanandan** [comment]
Hi, @thekalinga. I wanted to share a little bit of the background.

Skipper is a lightweight library; it's a Boot application. The primary goal of this project was to fulfill the CD gaps in Spring Cloud Data Flow (SCDF). For instance, you can build/run a streaming pipeline made of Spring Cloud Stream apps in SCDF; however, to rolling-upgrade an app or a series of them in a production setting without interrupting the data processing, our users have had to switch to the cloud platform and use its blue-green deployment model. And that, we wanted to simplify. The current approach addresses this gap via native DSL commands/APIs exposed in SCDF that interacts with Skipper behind the scenes. 

While doing so, we realized it could be a general purpose tooling that can be used to manage a standalone Boot application's deployment lifecycle, too.

Lastly, we are not trying to compete with Spinnaker or any other CI/CD tooling. Each of those systems come with comprehensive feature capabilities, no doubt. We wanted Skipper to be an alternative for situations that do not require a lot of moving parts operationally. More importantly, we wanted it to be a lightweight companion-server for SCDF needs.

**Comment by markpollack** [comment]
I don't think you digested my first sentence - 

`Skipper provides a declarative templating mechanism to describe the collection of Spring Boot apps to deploy and also a mechanism to discover/search for existing Spring Boot apps.`

Also, given the org/space model of most PCF users, e.g. their 'universe' are apps in that space, deploying spinnaker to manage a single space is too heavyweight.  8 spinnaker apps to update 3 spring boot apps is not going to fly with customers.

Ironically, I lead the charge (over two years ago, 10/15 is my first email on the topic with Andrew Glover) to have Pivotal invest in a Cloud Foundry version for Spinnaker, so it is not like I am not familiar with it.  After quite a long investment Pivotal decided not to provide Spinnaker support for our customers.  So we had to do something to support the Data Flow user case. Rather than have it baked into Data Flow, it was felt there could be some more generic use, the result is Skipper.  For example, we can template directly PCF manifest files and also create 'service manifests' for PCF, so that one can describe in some yml file what apps and services to install.  That isn't something in scope for Spinnaker and is quite a valid feature to build.  Of note, that decision is currently being revisited (I just work here :) ) so maybe once that work is done we will have Data Flow integrate with Spinnaker - a POC of an AppDeployer implementation that delegated to Spinnaker was done a while ago, so there is (at least) one way.

So there are features unique to Skipper, HELM inspired, and looks to be working quite well for our use cases.  Some feedback from customers/users at SpringOne (who in fact had tried Spinnaker and ditched it) felt Skipper would be flexible enough for them to adopt.

**Comment by thekalinga** [comment]
@sabbyanandan @markpollack 

Thanks for your detailed explanations & Glad to know you guys are looking at Spinnaker aswell when you progress on Skipper front.

As far I remember from documentation, Spinnaker is not production grade w.r.t upgrade, rollback & deployment (tho there is a toy grade upgrade available as of now). The documentation mentioned that there is a planned integration with statemachine library to support all of these in the future.

Will check back if there are any future developments in Spinnaker space.
