### ISSUE TITLE
Document configuration options for skipper.yml

### ISSUE THREAD

**Issue by Fitzoh** [spring-cloud/spring-cloud-skipper#542]
I'm starting to play around with skipper, and was trying to figure out how to wire it up the server portion to our pcf instance.

It doesn't appear that there is a configuration reference in the main docs, and it took me a while to find a sample config inside the git repo.

It'd be nice if there was an easy reference (similar to [the spring boot appendix](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html), or a link to some of the relevant `ConfigurationProperties` files.

**Comment by sabbyanandan** [comment]
Hi, @Fitzoh. We have a Cloud Foundry section in the reference guide and that includes a [sample manifest](https://docs.spring.io/spring-cloud-skipper/docs/1.0.0.RELEASE/reference/htmlsingle/#skipper-installation-cloudfoundry). Is that what you were looking for? 

Also, Skipper builds upon the platform-specific Spring Cloud Deployer implementation, so in CF, all that is available in [`CloudFoundryDeploymentProperties`](https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/blob/master/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java), is also available for use in Skipper.

**Comment by Fitzoh** [comment]
Yeah, that is blatantly obvious and I have no idea how I missed it 🙁.... I promise I spent an absurd amount of time flipping through the multi-page docs

**Comment by Fitzoh** [comment]
Although comparing the sample manifest to `CloudFoundryDeploymentProperties`, I don't quite get some of the nesting...
Why is it split up into `connection` and `deployment`, and why is `domain` part of connection?

**Comment by sabbyanandan** [comment]
OK, yeah, the reasoning behind the nesting is explained [here](https://docs.spring.io/spring-cloud-skipper/docs/1.0.0.RELEASE/reference/htmlsingle/#using-platforms). 

One of the main goals of Skipper is to support multiple platform backends. You can configure "n" number of CF, k8S, or both. Because each platform (i.e., cf, k8s) can have multiple backend accounts, we require the prefix `SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_<PLATFORM_NAME>_ACCOUNTS_[default]_CONNECTION_` and then followed by platform-specific properties. There can be connection and deployment properties, and they are available for overrides, too. Here's an example for CF:

```
    SPRING_CLOUD_SKIPPER_SERVER_ENABLE_LOCAL_PLATFORM: false
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[dev]_CONNECTION_URL: https://domain.io/
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[dev]_CONNECTION_ORG: scdf-ci
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[dev]_CONNECTION_SPACE: space-sabby
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[dev]_CONNECTION_DOMAIN: cfapps.app.io
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[dev]_CONNECTION_USERNAME: foo
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[dev]_CONNECTION_PASSWORD: foo
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[dev]_CONNECTION_SKIP_SSL_VALIDATION: false
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[dev]_CONNECTION_STREAM_ENABLE_RANDOM_APP_NAME_PREFIX: false
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[dev]_DEPLOYMENT_SERVICES: rabbit
```

(where, `<PLATFORM_NAME>` is  either LOCAL, CLOUDFOUNDRY, OR KUBERNETES; `[dev]` is the account name in my example; "DEPLOYMENT" token tells the cf-deployer to automatically also bind the service named `rabbit` to the deployed packages)

**Comment by sabbyanandan** [comment]
@Fitzoh: I believe this issue has been adequately discussed here and on gitter. For other questions, feel free to open a new thread in SO or ping us on gitter.
