### ISSUE TITLE
Forward-port duplicate profile fix from 1.0.x to 1.1.x

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#765]
We have [missed](https://github.com/spring-cloud/spring-cloud-skipper/blob/1.1.x/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/DeployerInitializationService.java#L63) to forward-port https://github.com/spring-cloud/spring-cloud-skipper/commit/c071772af3a826bf3500fdea7df3a6cb6c79c71e to 1.1.x. It is already in 2.0.x, however.

And because of this reason, on v1.1.2, we continue to see `default` showing up in the platform-list even when `SPRING_CLOUD_SKIPPER_SERVER_ENABLE_LOCAL_PLATFORM` is set to "false".

**Comment by markpollack** [comment]
I had to reason through this logic for the single server merge in SCDF and came up with the following solution that ins't ideal, but seems easier to reason about.   We can skill keep `SPRING_CLOUD_SKIPPER_SERVER_ENABLE_LOCAL_PLATFORM` so that configurations on PCF/K8s can be sure a local deployer will never be used.  However, the creation of the `default` local deploy is moved into the DeployerInitializationService and created only if there are no deployers defined at all. 

I think for M2, we can try to add additional checks when on PCF/K8s so that we can remove the use of 'enable local platform' and fail fast if skipper is configured with a local deployer when running on pcf/k8s.

**Comment by ilayaperumalg** [comment]
This specific change was already fixed via https://github.com/spring-cloud/spring-cloud-skipper/commit/03c70bd45bbf74628ec9349679d39efe96221256#diff-0c01f886929eb22cb0d47b640e349e4d. 

Hence this can be closed.
